# Generated by Django 3.1.4 on 2020-12-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.CharField(max_length=5000, verbose_name='Суть обращения')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default='', editable=False, max_length=50, verbose_name='GUID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(editable=False, max_length=50, verbose_name='GUID')),
                ('date', models.DateTimeField(default='', verbose_name='Дата документа')),
                ('number', models.CharField(default='', max_length=50, verbose_name='Номер документа')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10, verbose_name='Статус выполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('directory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.directory')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            bases=('CSMobile_site.directory',),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('directory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.directory')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
            ],
            bases=('CSMobile_site.directory',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('directory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.directory')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            bases=('CSMobile_site.directory',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.document')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.contact', verbose_name='Клиент')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.contractor', verbose_name='Контрагент')),
                ('customer_contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.customercontact', verbose_name='Контакты с клиентом')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.employee', verbose_name='Исполнитель')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.status', verbose_name='Статус обращения')),
            ],
            bases=('CSMobile_site.document',),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.contact', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.employee', verbose_name='Сотрудник'),
        ),
    ]
