# Generated by Django 3.1.5 on 2021-01-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSMobile_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='customer',
            new_name='contractor',
        ),
        migrations.AlterField(
            model_name='directory',
            name='guid',
            field=models.CharField(default='', max_length=50, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default='', null=True, verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='guid',
            field=models.CharField(max_length=50, null=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Номер документа'),
        ),
    ]
