# Generated by Django 3.1.4 on 2020-12-11 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSMobile_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.CharField(max_length=5000, verbose_name='Суть обращения')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default='', verbose_name='Дата документа')),
                ('num', models.CharField(max_length=50, verbose_name='Номер документа')),
            ],
        ),
        migrations.CreateModel(
            name='HandBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10, verbose_name='Статус выполнения')),
            ],
        ),
        migrations.DeleteModel(
            name='FinalDB',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('handbook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.handbook')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            bases=('CSMobile_site.handbook',),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('handbook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.handbook')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
            ],
            bases=('CSMobile_site.handbook',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('handbook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.handbook')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            bases=('CSMobile_site.handbook',),
        ),
        migrations.AddField(
            model_name='costumercontact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='costumercontact',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.employee', verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CSMobile_site.document')),
                ('contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.costumercontact', verbose_name='Контакты с клиентом')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.contractor', verbose_name='Контрагент')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.employee', verbose_name='Исполнитель')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CSMobile_site.status', verbose_name='Статус обращения')),
            ],
            bases=('CSMobile_site.document',),
        ),
    ]
