# Generated by Django 3.1.5 on 2021-01-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSMobile_site', '0004_auto_20210111_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
